version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    container_name: "users-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=onay
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
  
  api:
    build: .
    container_name: "users-rest-api"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "1234"
      DB_DB: "onay"
      DB_HOST: "localhost"
      DB_TABLE: "users"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge